[feat] add split_dim arg to reversible, remove retain_grad, add benchmark_reversible
facebookresearch/xformers pull request #45
Opened 2021-10-27 21:17 UTC by ClashLuke

This PR removes the repeated chunk and cat operations in xformers' RevNet code. This way, the RevNet implementation will become a little bit faster.\
I'd strongly recommend calling a library like [MemCNN](https://github.com/silvandeleemput/memcnn) or [RevLib](https://github.com/ClashLuke/revlib) directly as they make it easier to switch the coupling function and generally give the user more freedom.

Unfortunately, I can't sign the CLA at the moment, as it keeps saying
> Sorry, something went wrong.
> We're working on getting this fixed as soon as we can.

2021-10-29 20:50 UTC, dianaml0 requested changes
Thanks a lot @ClashLuke for your contribution and for testing out the impact of these changes to reversible layers! The benchmark is a really great addition! It seems like removing the `cat` and `chunk` operations didn't have the expected speed up for some reason - perhaps we can merge in the benchmarking code but leave `reversible.py` as it was for the sake of simplicity?

2021-10-29 20:53 UTC, ClashLuke commented on xformers/components/reversible.py
> +        x1, x2 = x.chunk(2, 2)
Following MemCNN's and RevLib's API, I just made it a parameter with the default set to -1.

2021-10-29 22:48 UTC, ClashLuke commented
I just gave it a try on a rented A100, and it seems a little faster with the current setup, and it seems like the speedup is negligible, especially for large batch sizes. If you find the original code simpler, let's revert.


<details>
<summary>Batch * Sequence in (16ki, 2ki, 128) </summary>

```
Upstream:

 --- Type: torch.float16 --- 
| Units: runtime in ms, lower is better          |Batch=16384, Features=32, Depth=4|Batch=16384, Features=32, Depth=32|Batch=16384, Features=32, Depth=256|Batch=2048, Features=256, Depth=4|Batch=2048, Features=256, Depth=32|Batch=2048, Features=256, Depth=256|Batch=128, Features=4096, Depth=4|Batch=128, Features=4096, Depth=32|Batch=128, Features=4096, Depth=256|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|residual - fw                                   |0.17                |2.61                |33.81               |0.16                |4.15                |30.77               |0.42                |3.25                |32.05               |
|reversible - fw                                 |0.27                |6.52                |56.69               |0.39                |5.55                |52.31               |0.44                |6.79                |56.95               |


 --- Type: torch.float32 --- 
| Units: runtime in ms, lower is better          |Batch=16384, Features=32, Depth=4|Batch=16384, Features=32, Depth=32|Batch=16384, Features=32, Depth=256|Batch=2048, Features=256, Depth=4|Batch=2048, Features=256, Depth=32|Batch=2048, Features=256, Depth=256|Batch=128, Features=4096, Depth=4|Batch=128, Features=4096, Depth=32|Batch=128, Features=4096, Depth=256|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|residual - fw                                   |0.17                |2.41                |29.93               |0.18                |2.51                |28.32               |0.76                |6.01                |47.60               |
|reversible - fw                                 |0.18                |5.97                |42.80               |0.19                |6.34                |41.91               |0.78                |6.08                |47.86               |


 --- Type: torch.float16 --- 
| Units: runtime in ms, lower is better          |Batch=16384, Features=32, Depth=4|Batch=16384, Features=32, Depth=32|Batch=16384, Features=32, Depth=256|Batch=2048, Features=256, Depth=4|Batch=2048, Features=256, Depth=32|Batch=2048, Features=256, Depth=256|Batch=128, Features=4096, Depth=4|Batch=128, Features=4096, Depth=32|Batch=128, Features=4096, Depth=256|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|residual - fw+bw                                |1.47                |10.97               |115.48              |0.94                |14.53               |194.51              |2.16                |14.96               |119.33              |
|reversible - fw+bw                              |3.91                |31.17               |225.91              |3.06                |35.75               |241.17              |3.47                |32.27               |217.62              |


 --- Type: torch.float32 --- 
| Units: runtime in ms, lower is better          |Batch=16384, Features=32, Depth=4|Batch=16384, Features=32, Depth=32|Batch=16384, Features=32, Depth=256|Batch=2048, Features=256, Depth=4|Batch=2048, Features=256, Depth=32|Batch=2048, Features=256, Depth=256|Batch=128, Features=4096, Depth=4|Batch=128, Features=4096, Depth=32|Batch=128, Features=4096, Depth=256|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|residual - fw+bw                                |1.31                |11.86               |78.94               |0.76                |13.88               |87.93               |3.71                |26.66               |212.21              |
|reversible - fw+bw                              |3.60                |28.95               |230.99              |3.11                |24.63               |216.43              |4.22                |33.24               |264.72              |

========================

Proposed:

 --- Type: torch.float16 --- 
| Units: runtime in ms, lower is better          |Batch=16384, Features=32, Depth=4|Batch=16384, Features=32, Depth=32|Batch=16384, Features=32, Depth=256|Batch=2048, Features=256, Depth=4|Batch=2048, Features=256, Depth=32|Batch=2048, Features=256, Depth=256|Batch=128, Features=4096, Depth=4|Batch=128, Features=4096, Depth=32|Batch=128, Features=4096, Depth=256|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|residual - fw                                   |0.17                |3.62                |26.28               |0.16                |3.91                |33.23               |0.42                |3.74                |31.64               |
|reversible - fw                                 |0.15                |4.90                |44.41               |0.37                |7.11                |49.51               |0.44                |5.00                |44.59               |


 --- Type: torch.float32 --- 
| Units: runtime in ms, lower is better          |Batch=16384, Features=32, Depth=4|Batch=16384, Features=32, Depth=32|Batch=16384, Features=32, Depth=256|Batch=2048, Features=256, Depth=4|Batch=2048, Features=256, Depth=32|Batch=2048, Features=256, Depth=256|Batch=128, Features=4096, Depth=4|Batch=128, Features=4096, Depth=32|Batch=128, Features=4096, Depth=256|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|residual - fw                                   |0.16                |3.36                |34.08               |0.17                |3.42                |27.66               |0.76                |6.00                |47.43               |
|reversible - fw                                 |0.18                |4.47                |48.93               |0.19                |6.34                |43.61               |0.78                |6.76                |47.71               |


 --- Type: torch.float16 --- 
| Units: runtime in ms, lower is better          |Batch=16384, Features=32, Depth=4|Batch=16384, Features=32, Depth=32|Batch=16384, Features=32, Depth=256|Batch=2048, Features=256, Depth=4|Batch=2048, Features=256, Depth=32|Batch=2048, Features=256, Depth=256|Batch=128, Features=4096, Depth=4|Batch=128, Features=4096, Depth=32|Batch=128, Features=4096, Depth=256|
|------------------------------------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|residual - fw+bw                                |1.38                |10.50               |89.10               |0.69                |10.65               |100.32              |2.15                |15.35               |118.91              |
|reversible - fw+bw                              |3.54                | [...]

2021-10-29 23:27 UTC, blefaudeux commented
@ClashLuke thanks for the changes and sorry for the broken test, should be fixed now if you rebase onto main :/ really sorry about the experience

2021-10-29 23:34 UTC, blefaudeux approved these changes
Looks great to me, thanks again @ClashLuke  !

2021-11-01 17:28 UTC, dianaml0 approved these changes
Looks great!

2021-11-01 17:35 UTC, merged